#include "timing.inc"
module test_alphas
  use types
  use unit_tests
  use qcd_coupling
  implicit none

contains

  subroutine unit_tests_alphas()
    implicit none
    integer  :: nloop

    !-- reference results generated by unit-tests/gen-alphas-ref.py
    real(dp), parameter :: mc=1.670000_dp, mb=4.780000_dp, mt=172.570000_dp, mz=91.187600_dp
    real(dp), parameter :: alphas_mz=0.118000_dp
    real(dp), parameter :: Qvals(*) = [1.000000_dp, 3.000000_dp, 9.000000_dp, 10000.000000_dp]
    real(dp), parameter :: ref_4loop_vfn(*) = [4.830588330944e-01_dp, 2.536785837279e-01_dp, 1.827496107358e-01_dp, 7.181749539235e-02_dp]
    !-- end of reference results

    type(running_coupling) :: alphas_vfn, alphas_nf4
    real(dp) :: default_dt, Q, abs_tol = 1e-9_dp
    integer  :: iQ

    default_dt = DefaultCouplingDt()
    !call SetDefaultCouplingDt(0.1_dp*default_dt)

    call InitRunningCoupling(alphas_vfn, alphas_mz, Q=mz, quark_masses=(/ mc, mb, mt /), nloop=4)
    call InitRunningCoupling(alphas_nf4, alphas_vfn%Value(2.0_dp), Q=2.0_dp, fixnf=4, nloop=4)

    do iQ = 1, size(Qvals)
      Q = Qvals(iQ)
      call check_approx_eq_0d("alphas_vfn at Q="//trim(to_string(Q)), alphas_vfn%Value(Q), ref_4loop_vfn(iQ), abs_tol)
    end do

    ! make sure that extraction outside of the range with fixnf works too
    call check_approx_eq("alphas_nf4_1GeV", alphas_nf4%Value(1.0_dp), alphas_vfn%Value(1.0_dp, fixnf=4), 1e-7_dp)
    call check_approx_eq("alphas_nf4_9GeV", alphas_nf4%Value(9.0_dp), alphas_vfn%Value(9.0_dp, fixnf=4), 1e-7_dp)

    TIME_START("alphas_vfn",10**7)
    real(dp) :: sum_alphas = 0.0_dp
    TIME_LOOP
      sum_alphas = sum_alphas + alphas_vfn%Value(Qvals(mod(irep,size(Qvals))+1))
      !sum_alphas = sum_alphas + alphas_vfn%Value(6.0_dp)
    TIME_END(sum_alphas)

  end subroutine unit_tests_alphas

end module test_alphas