#!/bin/bash
#
# Script that runs a quick check that the results are sensible
# 
# Run it from the top-level directory as scripts/check
#
# Created by GPS on 2009-09-05 and subsequently adapted by AK.
#----------------------------------------------------------------------

# list of tests to run:
# - for a test labelled $test, there should be a reference output file
#   $test.default_output
tests=(example_f90/tabulation_example \
       example_f90/tabulation_example_qed \
       example_f90/tabulation_example_qed_streamlined \
       example_f90/structure_functions_example \
       example_f90/structure_functions_example_flavour \
       )
       #example_f90/tabulation_example_up_and_down

for test in ${tests[@]}; do
  echo
  echo '*****************************************************************'
  echo '    ' Doing check with $test
  echo '*****************************************************************'
  echo 
  ($test | tee check.tmp.new-pregrep) || exit 1;
  
  grep -vi -e '^ *[a-z]' -e '^ *$' check.tmp.new-pregrep > check.tmp.new
  grep -vi -e '^ *[a-z]' -e '^ *$' $test.default_output > check.tmp.orig
  
  diff check.tmp.new check.tmp.orig > check.tmp.diff
  checkwc=`cat check.tmp.diff| wc -l `
  
  echo
  if [ $checkwc == "0" ] 
  then
    echo check PASSED
    rm -f check.tmp.new check.tmp.orig check.tmp.diff check.tmp.new-pregrep
  else
    echo check FAILED: look at 'check.tmp.*' to see differences
    exit 1;
  fi
  
done
