#!/bin/sh
# Script to coordinate generation of makefiles.
#
# Run ./mkmk to first create a makefile for this directory.
#
# Subsequently typing "make make" will update the makefile
# 
# Configuration information for LHAPDF and the compiler are set below.
# Note that the compiler can also be set via a file ".compiler" in this
# directory containing the name of your preferred f95 compiler.

# default compiler (g95, or that specified in .compiler)
compiler=""

# alternatively set the compiler here "-comp <compiler_name>"
#compiler="-comp g95"


../scripts/makef95makefile  libhoppet_v1.a  $compiler --install-script=../scripts/install-sh -remake "./mkmk"



#makePNEW.perl  libdglap.a
